---
- hosts: all

  tasks:
   -  name: Create a login user
      user:
        name: amit
        password: password
        state: present
        shell: /bin/bash
        createhome: yes
        home: /home/amit
   -  name: ensure file exists
      copy:
        dest: "/home/aaa/hello.txt"
        content: "hi"
       
